<?php
//SE CREA VARIABLE SERVIDOR PARA NOMBRAR EL SERVIDOR QUE USAREMOS;
$servidor="mysql:dbname=".BD.";host=".SERVIDOR;


try{
//SE CREA LA VARIABLE PDO PARA INCORPORAR EL SERVIDOR Y EN GENERAL NUESTRA BASE DE DATOS;
$pdo = new PDO($servidor,USUARIO,PASSWORD,
array(PDO::MYSQL_ATTR_INIT_COMMAND=>"SET NAMES utf8")

);

}catch(PDOException $e){
 
}

?>